import { useState } from "react";
import { ShieldCheck, Lock, Eye, AlertTriangle } from "lucide-react";
import { cn } from "../lib/utils";

// Mga privacy settings na ipinakita sa page — bawat isa ay may id, label, description, at on/off state
const defaultSettings = [
  { id: "mask_emails",   label: "Mask Email Addresses",  description: "Generated emails won't contain real TLDs or recognizable patterns", enabled: true },
  { id: "no_real_names", label: "Exclude Real Names",    description: "Avoid generating names that match entries in common name databases", enabled: true },
  { id: "synthetic_ids", label: "Synthetic IDs Only",    description: "All IDs are generated synthetically and cannot be reverse-mapped",   enabled: false },
  { id: "no_pii",        label: "Strict No-PII Mode",    description: "Automatically detect and exclude any personally identifiable field types", enabled: false },
  { id: "local_gen",     label: "Local Generation",      description: "Data is generated locally in your browser, never sent to servers",   enabled: false },
];

export default function PrivacyMode() {
  // Naka-track natin dito yung on/off state ng bawat privacy setting
  const [settings, setSettings] = useState(defaultSettings);

  // Kapag pinindot ang toggle, binabago natin yung enabled na value ng tamang setting
  const toggle = (id: string) => setSettings(settings.map(s => s.id === id ? { ...s, enabled: !s.enabled } : s));

  return (
    <div className="space-y-4">
      <div>
        <p className="text-xs text-gray-400">Control how your data is generated and handled</p>
      </div>

      {/* Info banner na nagpapaliwanag na synthetic ang lahat ng data — walang tunay na personal info */}
      <div className="bg-purple-50 border border-purple-100 rounded-xl p-4 flex items-start gap-3">
        <ShieldCheck className="w-5 h-5 text-purple-600 flex-shrink-0 mt-0.5" />
        <div>
          <p className="text-sm font-medium text-gray-900">Privacy-first by design</p>
          <p className="text-xs text-gray-500 mt-0.5">All data generated by SynthCS is completely synthetic. No real personal information is ever used or stored.</p>
        </div>
      </div>

      {/* Lista ng mga toggle switches — isang setting bawat row */}
      <div className="bg-white border border-gray-100 rounded-xl divide-y divide-gray-50 overflow-hidden shadow-sm">
        {settings.map((option) => (
          <div key={option.id} className="flex items-center justify-between px-5 py-4">
            <div className="flex items-start gap-3">
              {/* Nagbabago ang icon depende kung naka-on o naka-off ang setting */}
              <div className={cn("w-7 h-7 rounded-lg flex items-center justify-center mt-0.5", option.enabled ? "bg-purple-50" : "bg-gray-100")}>
                {option.enabled ? <Lock className="w-3.5 h-3.5 text-purple-600" /> : <Eye className="w-3.5 h-3.5 text-gray-400" />}
              </div>
              <div>
                <p className="text-sm font-medium text-gray-800">{option.label}</p>
                <p className="text-xs text-gray-400 mt-0.5">{option.description}</p>
              </div>
            </div>
            {/* Toggle switch — purple kapag naka-on, gray kapag naka-off */}
            <button onClick={() => toggle(option.id)}
              className={cn("relative w-10 h-5 rounded-full transition-colors flex-shrink-0 ml-4", option.enabled ? "bg-purple-600" : "bg-gray-200")}>
              <span className={cn("absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition-transform", option.enabled ? "translate-x-5" : "translate-x-0.5")} />
            </button>
          </div>
        ))}
      </div>

      {/* Babala na baka mababa ang kalidad ng data kapag masyadong strict ang privacy settings */}
      <div className="bg-yellow-50 border border-yellow-100 rounded-xl p-4 flex items-start gap-3">
        <AlertTriangle className="w-4 h-4 text-yellow-500 flex-shrink-0 mt-0.5" />
        <p className="text-xs text-yellow-800">Enabling strict privacy modes may reduce the realism of generated data. Use only when compliance requirements mandate it.</p>
      </div>

      {/* Save button — hindi pa ito konektado sa backend */}
      <div className="flex justify-end">
        <button className="px-4 py-2 bg-purple-600 text-white rounded-md text-xs font-medium hover:bg-purple-700 transition-colors">Save Privacy Settings</button>
      </div>
    </div>
  );
}
